version: '3'
services:
  app:
    container_name: premier-league
    build: .
    links:
      - redis
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - mongo
  redis:
    container_name: redis
    image: 'redis:alpine'
    expose:
      - 6379
  mongo:
    container_name: mongo
    image: mongo
